### ISSUE TITLE
Crash on Server - HCFurnace TileEntitySpecialRenderer

### ISSUE THREAD

**Issue by nmarshall23** [BetterWithMods/BetterWithMods#715]
pastebin of the crash report, https://pastebin.com/A3snLhyQ

Looking at source code, `Hardcore.java:71` is HCFurnace doesn't matter if I disable that. Still crashes.

~~~
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Better With Mods (betterwithmods)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer
    at betterwithmods.module.hardcore.Hardcore.addFeatures(Hardcore.java:71)
    at betterwithmods.module.Module.setupConfig(Module.java:74)
~~~

**Comment by primetoxinz** [comment]
Pushed a fix
