### ISSUE TITLE
1.10.2 Dedicated Server Log Spam - Timeout

### ISSUE THREAD

**Issue by Matmatix** [BetterWithMods/BetterWithMods#794]
When using the Chunk Pregenerator with Realistic Terrain Generation and BiomeTweaker, I get this spammed repeatedly in the server log after a certain point.  Whenever a client attempts to connect, they get timed out.

```
[18:09:58] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	... 22 more
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: java.lang.InstantiationException: betterwithmods.world.BWComponentScatteredFeaturePieces$DesertPyramid
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at java.lang.Class.newInstance(Class.java:427)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at net.minecraft.world.gen.structure.MapGenStructureIO.func_143032_b(SourceFile:89)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at net.minecraft.world.gen.structure.StructureStart.func_143020_a(StructureStart.java:105)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at net.minecraft.world.gen.structure.MapGenStructureIO.func_143035_a(SourceFile:76)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at net.minecraft.world.gen.structure.MapGenStructure.func_143027_a(MapGenStructure.java:247)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at net.minecraft.world.gen.structure.MapGenStructure.func_180706_b(MapGenStructure.java:156)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at thaumcraft.common.world.ThaumcraftWorldGenerator.generateNodes(ThaumcraftWorldGenerator.java:146)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at thaumcraft.common.world.ThaumcraftWorldGenerator.generateAll(ThaumcraftWorldGenerator.java:350)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at thaumcraft.common.world.ThaumcraftWorldGenerator.worldGeneration(ThaumcraftWorldGenerator.java:69)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at thaumcraft.common.world.ThaumcraftWorldGenerator.generate(ThaumcraftWorldGenerator.java:57)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at pregenerator.impl.processor.ChunkFile.populate(ChunkFile.java:86)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at pregenerator.impl.processor.ChunkFile$ChunkFileEntry.process(ChunkFile.java:250)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at pregenerator.impl.processor.ChunkProcessor.onServerTickEvent(ChunkProcessor.java:97)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_538_ChunkProcessor_onServerTickEvent_ServerTickEvent.invoke(.dynamic)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[18:09:58] [Server thread/INFO] [STDERR/]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143032_b:93]: 	at java.lang.Thread.run(Thread.java:748)
[18:09:58] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NoSuchMethodException: betterwithmods.world.BWComponentScatteredFeaturePieces$DesertPyramid.<init>()
[18:09:58] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at java.lang.Class.getConstructor0(Class.java:3082)
[18:09:58] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at java.lang.Class.newInstance(Class.java:412)
[18:09:58] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	... 22 more
```
Latest log is 8 GB so I took out that snippet. Let me know if you need more information.
Here are the mods we have: [mods.txt](https://github.com/BetterWithMods/BetterWithMods/files/1809596/mods.txt)

**Comment by DaedalusGame** [comment]
this is a 1.10 issue and 1.10 is no longer supported, sorry
you can try disabling HCStructures in the config if you don't especially care about it
