### ISSUE TITLE
Won't load on SMP

### ISSUE THREAD

**Issue by OfficiallyBrown** [BetterWithMods/BetterWithMods#802]
I installed the forge server, ran it, got it all running.
I put the BWM jar in the mods folder and when I launched the server again, it just wasnt loaded. Also it didn't create the config files or anything else either

The only error that came up is this, 

[17:04:19 ERROR]: Exception handling console input
java.io.IOException: The handle is invalid
	at java.io.FileInputStream.readBytes(Native Method) ~[?:1.8.0_151]
	at java.io.FileInputStream.read(Unknown Source) ~[?:1.8.0_151]
	at java.io.BufferedInputStream.read1(Unknown Source) ~[?:1.8.0_151]
	at java.io.BufferedInputStream.read(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source) ~[?:1.8.0_151]
	at sun.nio.cs.StreamDecoder.read(Unknown Source) ~[?:1.8.0_151]
	at java.io.InputStreamReader.read(Unknown Source) ~[?:1.8.0_151]
	at java.io.BufferedReader.fill(Unknown Source) ~[?:1.8.0_151]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_151]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_151]
	at nz$2.run(SourceFile:100) [minecraft_server.1.12.2.jar:?]

**Comment by primetoxinz** [comment]
Can you send the forge-server-latest.log?

**Comment by OfficiallyBrown** [comment]
[fml-server-latest.log](https://github.com/BetterWithMods/BetterWithMods/files/1843504/fml-server-latest.log)

**Comment by OfficiallyBrown** [comment]
I did, and I believe the same error came up, but it still loaded and allowed me to play, so it must've slipped my mind. I apologise, I'll head over to the forget forums and see what I can muster

**Comment by OfficiallyBrown** [comment]
I got it working, feel free to close
