### ISSUE TITLE
Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by MacKey-255** [BetterWithMods/BetterWithMods#921]
I don't speark english, ok!
This error no respawn me, in play game:
(Este error no me permite respawnear en el juego, tanto cliente como servidor)
[17:05:22] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at betterwithmods.module.gameplay.PlayerDataHandler$PlayerInfo.getCapability(PlayerDataHandler.java:93) ~[PlayerDataHandler$PlayerInfo.class:?]
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:108) ~[CapabilityDispatcher.class:?]
	at net.minecraft.entity.Entity.getCapability(Entity.java:3083) ~[vg.class:?]
	at net.minecraft.entity.EntityLivingBase.getCapability(EntityLivingBase.java:2949) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.getCapability(EntityPlayer.java:2682) ~[aed.class:?]
	at betterwithmods.module.gameplay.PlayerDataHandler.getPlayerInfo(PlayerDataHandler.java:58) ~[PlayerDataHandler.class:?]
	at betterwithmods.module.gameplay.PlayerDataHandler.clone(PlayerDataHandler.java:42) ~[PlayerDataHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_465_PlayerDataHandler_clone_Clone.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerClone(ForgeEventFactory.java:536) ~[ForgeEventFactory.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_193104_a(EntityPlayerMP.java:1176) ~[oq.class:?]
	at net.minecraft.server.management.PlayerList.func_72368_a(PlayerList.java:540) ~[pl.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147342_a(NetHandlerPlayServer.java:1117) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketClientStatus.func_148833_a(SourceFile:31) ~[lb.class:?]
	at net.minecraft.network.play.client.CPacketClientStatus.func_148833_a(SourceFile:8) ~[lb.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by primetoxinz** [comment]
I think I have found the error and made a fix for this.
I will make a release with the fix very soon.
